# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-21 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0007_auto_20170605_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderedScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
