# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_holiday', models.BooleanField()),
                ('use_workday', models.BooleanField()),
                ('use_monday', models.BooleanField()),
                ('use_tuesday', models.BooleanField()),
                ('use_wednesday', models.BooleanField()),
                ('use_thursday', models.BooleanField()),
                ('use_friday', models.BooleanField()),
                ('use_saturday', models.BooleanField()),
                ('use_sunday', models.BooleanField()),
                ('voice_type', models.CharField(max_length=50)),
                ('voice_emotion', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('message', models.TextField()),
                ('order', models.IntegerField()),
            ],
        ),
    ]
