# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_machine', '0002_scheduleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='voice_emotion',
            field=models.CharField(choices=[('neutral', 'neutral'), ('evil', 'evil'), ('good', 'good')], default='neutral', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='voice_type',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], default='primary', max_length=50),
        ),
    ]
