# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_machine', '0003_auto_20170311_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='message',
            field=models.TextField(help_text='Возможные замены: {{time}}, {{date}}, {{weekday}}.'),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='use_friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='use_monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='use_saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='use_sunday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='use_thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='use_tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='use_wednesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='voice_type',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('random', 'random')], default='primary', max_length=50),
        ),
    ]
