# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-21 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_machine', '0008_renderedscheduleitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renderedscheduleitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='renderedscheduleitem',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
