# Generated by Django 2.1.2 on 2018-10-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0009_auto_20181021_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='message',
            field=models.TextField(help_text='Возможные замены: {{time}}, {{date}}, {{weekday}}, {{weather_today}}, {{weather_tomorrow}}.'),
        ),
    ]
