# Generated by Django 2.1.3 on 2018-11-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_machine', '0010_auto_20181031_1625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RenderedScheduleItem',
        ),
    ]
